language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andrewleigh6/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andrewleigh6/docker-react npm run test
